<?php

/* install.html.twig */
class __TwigTemplate_1cec01cc2f672327895245d52719ca8e42847a0092177c27cfd77a7393d1f4a0 extends Twig_Template
{
    public function __construct(Twig_Environment $env)
    {
        parent::__construct($env);

        $this->parent = $this->env->loadTemplate("base.html.twig");

        $this->blocks = array(
            'content' => array($this, 'block_content'),
        );
    }

    protected function doGetParent(array $context)
    {
        return "base.html.twig";
    }

    protected function doDisplay(array $context, array $blocks = array())
    {
        $this->parent->display($context, array_merge($this->blocks, $blocks));
    }

    // line 3
    public function block_content($context, array $blocks = array())
    {
        // line 4
        echo "    <div id=\"login\">
        <div id=\"loginform\">
            <form method=\"post\">
                <div class=\"alert alert-info\">
                    <p>Thank you for installing Syonix Monolog Viewer. This little tool helps you to beautifully display log files generated by <a href=\"https://github.com/Seldaek/monolog\" target=\"_blank\" class=\"alert-link\">Monolog</a>.</p>
                    <p><strong>Please enter a password to be used to secure this applcation.</strong></p>
                </div>
                <?php
                    if(\$setupNomatch === true) {
                        echo '<div class=\"alert alert-danger alert-dismissable\"><b>Error</b> - The provided Passwords do not match.</div>';
                    } if(\$setupFailed === true) {
                        echo '<div class=\"alert alert-danger alert-dismissable\"><b>Error</b> - Could not save the password. Please make sure that the directory <code>/secure</code> is writable.</div>';
                    }
                ?>
                <input type=\"password\" class=\"form-control\" name=\"password\" placeholder=\"Password\">
                <input type=\"password\" class=\"form-control\" name=\"password-repeat\" placeholder=\"Repeat password\">
                <input type=\"submit\" class=\"btn btn-primary btn-block\" name=\"setup\" value=\"Create login\">
            </form>
        </div>
    </div>
";
    }

    public function getTemplateName()
    {
        return "install.html.twig";
    }

    public function isTraitable()
    {
        return false;
    }

    public function getDebugInfo()
    {
        return array (  31 => 4,  28 => 3,);
    }
}
